### ISSUE TITLE
Installed to web subfolders, Stylesheet not loeaded.

### ISSUE THREAD

**Issue by josestefan** [antedebaas/DMARC-Reports#14]
Hello,

Instead of using a new vhost on my apache config. I used the Alias directive.

Initially the icons on the left menu bar were HUGE. And I noticed that style.css file was not loading because it was linked as:
`<link href="/style.css" rel="stylesheet">`
(As seen by the browser's view source. Note the leading slash)

I don't know if the website is supposed to automatically detect and prepend any sub folder I would be using, but a quick glance at the source file, and it seems to be hard coded as-is.

In the meantime I've edited. the following file on my local setup, removing the leading slash, which temporarily fixes the problem.
`./templates/base.html.twig`

After editing I had to run the update.sh bash script.

I have some knowledge of PHP, but not enough to debug this in detail. I'm still configuring the tool. Need to setup the mail boxes.

**Comment by antedebaas** [comment]
Did you set the document_root to the public directory?
Or are you not running it on its own vhost?

**Comment by josestefan** [comment]
If you mean the Apache DocumentRoot Directive. I can't because the VHOST already has a website.
So I used the Alias directive

I didn't want to use a new vhost because I wanted to re-use my existing SSL certificate , which currently doesn't have wildcards.

Everything seemed fine except for the stylesheet link pointing to "/style.css"

**Comment by antedebaas** [comment]
Lots of links, buttons and forms will not work if this is not on its own vhost.
Also you need and mta-sts.yourdomain.ext anyway for the sts policy to work.

**Comment by Keeper-of-the-Keys** [comment]
Hey I was also just playing with this and didn't understand why some of the style was not 100% the solution is fairly simple: 
`href="./style.css"` instead of `href="/style.css"` in base.html.twig

As for non working buttons I have not encountered them so far by using the following apache config for the folder:
```
       Alias /dmarc /var/www/DMARC-SMTPTLS-Reports/public

        <Directory /var/www/DMARC-SMTPTLS-Reports/public>
                AllowOverride None
                Require all granted
                FallbackResource /dmarc/index.php
        </Directory>
```

I realize that I may want to create a true vhost later to implement mta-sts but at this point I have DANE, DMARC and DKIM and the fix to have this work is trivial.

/Edit - It may be wise to include a sha checksum even on a "local" resource like that when a misconfigured server serves the wrong style.css stuff breaks clearly instead of potentially working partially.

**Comment by antedebaas** [comment]
changing /style.css to ./style,css will have the style sheet break in all pages but the frontpage.
thus this will not work.
the project is written with virtual paths in mind and is intended to run on its own vhost.

using it like this is a dirty hack and i can not support that in any way as it will basicly break most of the functionality.

About the edit: yes. Good point
