### ISSUE TITLE
[Feature Request] Users, Report and UI

### ISSUE THREAD

**Issue by tobsowo** [antedebaas/DMARC-Reports#8]
Thank you for the wonderful work you're doing with this project. I would like to make some feature requests.

Users and Login
- Manually add users as admin
- User self password reset option on login
- Welcome email for new users to get verified

Reports
- Option to sort by: result, date, organization, reporter organization, domain
- Table sortable
- Click on the row to view the report instead of the 'Open Report' button alone
- Add disposition to the result column

Charts and Graphs over a time period
- View results over time in charts and graphs
- Pie Chart: SPF Alignment, DKIM Alignment, DMARC Passage
- Graph: SPF Results (soft fail, pass, none, fail), DKIM Results (pass, fail),  SPF and DKIM Alignment (true, false), DMARC Passage (true, false), Message Disposition (reject, quarantine, none)
- Count of all messages

**Comment by antedebaas** [comment]
This is -as said before- currently out of scope for the project.

**Comment by antedebaas** [comment]
@tobsowo i will have a look at this later.

**Comment by tobsowo** [comment]
Thank you.

**Comment by antedebaas** [comment]
> Users and Login
>     * Manually add users as admin
>     * User self password reset option on login
>     * Welcome email for new users to get verified

This project is intended as a self hosted solution, not a self-service portal.
the functionality that is there is because i needed some shielding and the framework provided this.

> Reports
>     * Option to sort by: result, date, organization, reporter organization, domain
>     * Table sortable
>     * Click on the row to view the report instead of the 'Open Report' button alone
>     * Add disposition to the result column

disposition is found under "Policy evaluation"
as for the rest, see my last comment below

> 
> Charts and Graphs over a time period
>     * View results over time in charts and graphs
>     * Pie Chart: SPF Alignment, DKIM Alignment, DMARC Passage
>     * Graph: SPF Results (soft fail, pass, none, fail), DKIM Results (pass, fail),  SPF and DKIM Alignment (true, false), DMARC Passage (true, false), Message Disposition (reject, quarantine, none)
>     * Count of all messages

This is way to much work and provides nothing more than eye candy.
Also there is nothing of value of historic data in this project. Only the latest report per submitter per domain provides useful information.

if you really want this in the project I am open to it, however I'm not gonna put in the effort myself.
you  are free to submit a pull request.

**Comment by tobsowo** [comment]
That's fine.
Thank you for the work you're doing.
